### ISSUE TITLE
Map all controller endpoints

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/elevator#115]
As we move into the new UI, we should:

- [ ] make a map of all of the controller endpoints
- [ ] describe where they're used
- [ ] flag which ones are unused by the VueJS interface
- [ ] Identify Stuff That's In Controllers Which Shouldn't Be (private methods and stuff)

**Comment by jxjj** [comment]
I think this is true...

In the new UI, all endpoints will be found in either:
- [router.ts](https://github.com/UMN-LATIS/elevator-ui/blob/develop/src/router.ts), or 
- [fetchers.ts](https://github.com/UMN-LATIS/elevator-ui/blob/develop/src/api/fetchers.ts)

What would be good next steps here? 

Should I add a php doc comment to a controller that's used by the new ui ( like [`@api`](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc-tags.md#51-api)? Or some other tag? `@deprecated` for non-used endpoints?

**Comment by cmcfadden** [comment]
I'm fine with just closing this, next step will be to move to Laravel anyways
