### ISSUE TITLE
Revise UMN header for elevator sites

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/elevator#152]
Old header (as seen on dcl.elevator.umn.edu) is the old branding, and relies on static assets being placed on the server. Doesn't work in the VueJS interface, I suspect because it relies on a <link> tag. (we should maybe allow <link> regardless) .. would be nice to replace with a minimal version of the new branding?

**Comment by jxjj** [comment]
Closing. Resolved in https://github.com/UMN-LATIS/elevator-ui/pull/255
